# This is a basic workflow to help you get started with Actions

name: CICD-pipeline-to-AWS
env:
  EB_PACKAGE_S3_BUCKET_NAME : "konstantin-agishev-awscicd"
  EB_APPLICATION_NAME       : "aws-cicd"
  EB_ENVIRONMENT_NAME       : "Prod"
  DEPLOY_PACKAGE_NAME       : "web_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-east-2"    

on:
  push:
    branches: 
      - master

jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    
    steps:
    - name: Git clone our repo 
      uses: actions/checkout@v1
    
    - name: Create zip deployment package
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

 
